name=ACD1200
version=1.0.0
author=Chipxa Technology Co., Ltd. (Công ty TNHH Công nghệ Chipxa)
maintainer=Chipxa Technology Co., Ltd. <contact@chipxa.com>
sentence=A library for the ACD1200 CO2 sensor.
paragraph=Supports reading CO2 concentration, average CO2, and printing raw packets using any Stream interface. Developed by Chipxa Technology.
category=Sensors
url=https://github.com/chipxatech/Chipxa-AirQualityMonitor
architectures=*
includes=ACD1200.h

