name=ACD1200
version=1.0.0
author=Admin
maintainer=Admin
sentence=A library for the ACD1200 CO2 sensor.
paragraph=Supports reading CO2 concentration, average CO2, and printing raw packets using any Stream interface.
category=Sensors
url=
architectures=*
includes=ACD1200.h
