name=APM10
version=1.0.0
author=Chipxa Technology Co., Ltd. (Công ty TNHH Công nghệ Chipxa)
maintainer=Chipxa Technology Co., Ltd. <contact@chipxa.com>
sentence=A library for the APM10 Particulate Matter (PM) sensor.
paragraph=Supports reading PM1.0, PM2.5, and PM10 concentration, and converting to EPA AQI (Air Quality Index) values using I2C or Serial interface. Developed by Chipxa Technology.
category=Sensors
url=https://github.com/chipxatech/Chipxa-AirQualityMonitor
architectures=*
includes=APM10.h

